name: Test on Android and iOS

on: [pull_request]

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Set up Node JS
        uses: actions/setup-node@v1
        with:
          node-version: "10.17.0"
      - name: Clean Packages
        run: |
          rm -rf node_modules
          npm cache clean --force
          rm -rf package-lock.json
      - name: Run Android Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: google_apis
          profile: pixel_3a
      # Install the Appium Server
      - name: Install the Appium Server
        run: npm install -g appium
      # List iOS Devices & Platforms
      - name: List iOS Devices & Platforms
        run: |
          xcrun simctl list
      - name: Execute tests
        run: Platform='both' RUNNER_LEVEL="parallel" CONFIG_FILE='./configs/config.properties' mvn clean -Dtest=Runner test -Dcheckstyle.skip
